In [15]:
'''
Complete Tactile Feedback code
'''

import sys
sys.path.insert(0, 'C:/Users/dema2/OneDrive/Desktop/PhD/Tactile-Feedback-Repo/Reflex-Fuzzy-Network')

from RFMN import ReflexFuzzyNeuroNetwork


In [16]:
# --- Import Modules --- #
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import time
import string
import random

In [17]:
data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\Tactile-Feedback-Repo\\Reflex-Fuzzy-Network\\Arduino_train_test_work.csv')

data = data.iloc[:,1:]

print(data, "\n\n\n")

X = data.iloc[:,:-1] # for every y (class) we get a 4-D array. E.g., I'm in the 5th dimension. 
y = data.iloc[:,-1] # same as saying y coresponds to the respective classes. E.g., w = 1,2 or 3.

print(X, "\n\n\n")
print(y, "\n\n\n")


       Force    Work  Label
0       0.00    0.00      1
1       0.00    0.00      1
2       0.00    0.00      1
3       0.00    0.00      1
4       0.00    0.00      1
...      ...     ...    ...
10795  21.40  213.95      9
10796  21.44  192.93      9
10797  21.44  171.50      9
10798  21.44  214.37      9
10799  21.40  192.56      9

[10800 rows x 3 columns] 



       Force    Work
0       0.00    0.00
1       0.00    0.00
2       0.00    0.00
3       0.00    0.00
4       0.00    0.00
...      ...     ...
10795  21.40  213.95
10796  21.44  192.93
10797  21.44  171.50
10798  21.44  214.37
10799  21.40  192.56

[10800 rows x 2 columns] 



0        1
1        1
2        1
3        1
4        1
        ..
10795    9
10796    9
10797    9
10798    9
10799    9
Name: Label, Length: 10800, dtype: int64 





In [18]:
scaler_min_max = MinMaxScaler(feature_range=(0.001, .99))
X_norm = scaler_min_max.fit_transform(X)

print(X.min)


<bound method NDFrame._add_numeric_operations.<locals>.min of        Force    Work
0       0.00    0.00
1       0.00    0.00
2       0.00    0.00
3       0.00    0.00
4       0.00    0.00
...      ...     ...
10795  21.40  213.95
10796  21.44  192.93
10797  21.44  171.50
10798  21.44  214.37
10799  21.40  192.56

[10800 rows x 2 columns]>


In [19]:
# Split the data between train and test. 
X_train, X_test, y_train, y_test = train_test_split( X_norm, y, test_size=0.33, random_state=42) # Split the data to 33% to test, and 66% to training
                                            #These value come in four 66X1 matrices for X_train and X_test
                                            # and one 66X1 matrix for y_train and y_test. 
                                            # random state = 42
print(" This is X_train \n", X_train, "\n" )
print(" This is X_test \n", X_test, "\n" )
print(" This is y_train \n", y_train, "\n" )
print(" This is y_test \n", y_test, "\n" )

 This is X_train 
 [[0.6838749  0.31097088]
 [0.001      0.001     ]
 [0.4526933  0.41137236]
 ...
 [0.67447521 0.33785537]
 [0.001      0.001     ]
 [0.49816748 0.44063915]] 

 This is X_test 
 [[0.52966915 0.11346972]
 [0.63535217 0.08177883]
 [0.96027665 0.34609938]
 ...
 [0.96357924 0.40902663]
 [0.51391831 0.48321234]
 [0.66075674 0.33742175]] 

 This is y_train 
 5792    5
678     1
2577    3
6839    6
3098    3
       ..
5734    5
5191    5
5390    5
860     1
7270    7
Name: Label, Length: 7236, dtype: int64 

 This is y_test 
 1254     2
9033     8
2523     3
10670    9
8637     8
        ..
10522    9
9260     8
3945     4
7333     7
9277     8
Name: Label, Length: 3564, dtype: int64 



In [20]:
y_train, y_test = y_train.values, y_test.values # Transpose the y_train and y_test data. 
                                # Essentailly we go from a 66X1 matrices to a 1x66 matrices. 
X_train, X_test = X_train.T, X_test.T # Transpose the X_train and X_test data. 
                                # Essentailly we go from four 66X1 matrices to four 1x66 matrices. 
# print(" This is X_train.T \n", X_train, "\n" )
# print(" This is X_test.T \n", X_test, "\n" )
# print(" This is y_train.values \n", y_train, "\n" )
# print(" This is y_test.values \n", y_test, "\n" )



print("X train \n", X_train)
print("Y train \n", y_train)
# print("X train len \n", len(X_train))
# print("Y train len \n", len(y_train))
print("X train shape \n", X_train.shape)
print("Y train shape\n", y_train.shape)


print("X test 1 \n", X_test)
print("Y test 1 \n", y_test)
# # # print("X test len \n", len(X_test))
# print("Y test len \n", len(y_test))
print("X test shape \n", X_test.shape)
print("Y test shape\n", y_test.shape)

X train 
 [[0.6838749  0.001      0.4526933  ... 0.67447521 0.001      0.49816748]
 [0.31097088 0.001      0.41137236 ... 0.33785537 0.001      0.44063915]]
Y train 
 [5 1 3 ... 5 1 7]
X train shape 
 (2, 7236)
Y train shape
 (7236,)
X test 1 
 [[0.52966915 0.63535217 0.96027665 ... 0.96357924 0.51391831 0.66075674]
 [0.11346972 0.08177883 0.34609938 ... 0.40902663 0.48321234 0.33742175]]
Y test 1 
 [2 8 3 ... 4 7 8]
X test shape 
 (2, 3564)
Y test shape
 (3564,)


In [21]:
# # # --- Declare network --- "
nn = ReflexFuzzyNeuroNetwork(gamma=1, theta=.1)
# '''
# X_trian after the X_train.T (transponse) is an "array [[column 1,column 2, column 3, column 4"]]
# y_train after the y_train.values (transpose) is an array[column 5]
# '''
# --- Train network --- #
nn.train(X_train, y_train)