In [72]:
# Use to learn and test the data and run the algorithm GRMMF
# --- Import Modules --- #
import sys, statistics, time, string, random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

sys.path.insert(0, 'C:/Users/dema2/OneDrive/Desktop/PhD/Tactile-Feedback-Repo/Reflex-Fuzzy-Network')
from RFMN import ReflexFuzzyNeuroNetwork

np.set_printoptions(threshold=5)


In [73]:
buffer_size = 149 
data_buffer = []

def median_filter(data):
    data_buffer.append(data)
    if len(data_buffer) > buffer_size:
        data_buffer.pop(0)  
    median_value = np.median(data_buffer)
    return median_value

def simulate_data_input(X):
    original_data = []
    filtered_data = []
    for element in np.nditer(X):
        data_point = element  
        filtered_point = median_filter(data_point)
        original_data.append(data_point)
        filtered_data.append(filtered_point)

    return original_data, filtered_data

In [74]:
# --- Import Iris data, split, and scale --- #
# data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\Arduino_train_test_labels.csv')
data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\Tactile-Feedback-Repo\\SaveModel\\Iris_feedback.csv')
data = data.iloc[:,1:]
X = data.iloc[:, :-1].values
y = data.iloc[:, 4].values

sepal_length = data.iloc[:, :-4].values
sepal_width = data.iloc[:, 1:-3].values
petal_length = data.iloc[:, 2:-2].values
petal_width = data.iloc[:, 3:-1].values

original_data, sepal_length_data = simulate_data_input(sepal_length)
original_data, sepal_width_data = simulate_data_input(sepal_width)
original_data, petal_length_data = simulate_data_input(petal_length)
original_data, petal_width_data = simulate_data_input(petal_width)

sepal_length_data = np.array(sepal_length_data)
sepal_width_data = np.array(sepal_width_data)
petal_length_data = np.array(petal_length_data)
petal_width_data = np.array(petal_width_data)

combined_array_X = np.vstack((sepal_length_data, sepal_width_data, petal_length_data, petal_width_data)).T

print("this is combined array \n", combined_array_X)

scaler_min_max = MinMaxScaler(feature_range=(0.001, 9))
X_norm = scaler_min_max.fit_transform(combined_array_X)
print("this is X_norm \n", X_norm)

this is combined array 
 [[5.1 5.8 3.  4.4]
 [5.  5.8 3.  4.4]
 [4.9 5.8 3.  4.4]
 ...
 [5.8 3.  4.3 1.3]
 [5.8 3.  4.3 1.3]
 [5.8 3.  4.4 1.3]]
this is X_norm 
 [[2.70070000e+00 9.00000000e+00 1.58905882e+00 9.00000000e+00]
 [1.80080000e+00 9.00000000e+00 1.58905882e+00 9.00000000e+00]
 [9.00900000e-01 9.00000000e+00 1.58905882e+00 9.00000000e+00]
 ...
 [9.00000000e+00 1.00000000e-03 8.47064706e+00 1.00000000e-03]
 [9.00000000e+00 1.00000000e-03 8.47064706e+00 1.00000000e-03]
 [9.00000000e+00 1.00000000e-03 9.00000000e+00 1.00000000e-03]]


In [75]:
# X_norm = (combined_array_X-combined_array_X.min())/(combined_array_X.max()-combined_array_X.min())
# print("this is X_norm \n", X_norm)


In [76]:

X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.33, random_state=42)                                     
X_train, X_test = X_train.T, X_test.T 
print(X_train)
nn = ReflexFuzzyNeuroNetwork(gamma=1, theta=.1)
nn.train(X_train, y_train)
print("Model is trained")
# --- Test Network --- #
y_predlr = nn.test(X_test,y_test)

print("done with testings")

[[5.40040000e+00 6.30030000e+00 2.70070000e+00 ... 9.00900000e-01
  5.40040000e+00 6.30030000e+00]
 [1.28657143e+00 9.65178571e-01 8.03582143e+00 ... 9.00000000e+00
  1.60796429e+00 1.28657143e+00]
 [1.58905882e+00 1.58905882e+00 1.00000000e-03 ... 1.58905882e+00
  1.05970588e+00 1.58905882e+00]
 [1.00000000e-03 1.00000000e-03 7.83883871e+00 ... 9.00000000e+00
  2.91290323e-01 1.00000000e-03]]
Model is trained
[2 1 3 ... 3 2 3]
done with testings


In [77]:
# predict_a = np.array([5.8, 3.0, 4.3, 1.3])
predict_a = np.array([5.8, 3.0,  4.4, 1.3])



new_predict_a = predict_a.reshape(1, 4)

print(new_predict_a)




[[5.8 3.  4.4 1.3]]


In [78]:
scaler_min_max = MinMaxScaler(feature_range=(0.001, 9))
predict_a_trans = scaler_min_max.fit_transform(new_predict_a)

predict_b = predict_a_trans.ravel()

print(predict_a_trans)
print(predict_b)








[[0.001 0.001 0.001 0.001]]
[0.001 0.001 0.001 0.001]


In [79]:
prediction = nn.predict(predict_b)

print(prediction)


1
