In [107]:
"""
# Use to learn and test the data and run the algorithm GRMMF
# --- Import Modules --- #
"""

# --- Import Modules --- #
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from RFMN import ReflexFuzzyNeuroNetwork
import time
import string
import random

np.set_printoptions(threshold=5)


In [108]:
# data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\iris_data_norm.csv')
# data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\iris_data_norm - 2 col.csv')
# data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\mydata_norm - 2 column.csv')
data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\Arduino_train_test_labels.csv')


data = data.iloc[:,1:]

# print(data)


X = data.iloc[:,:-1] # for every y (class) we get a 4-D array. E.g., I'm in the 5th dimension. 
y = data.iloc[:,-1] # same as saying y coresponds to the respective classes. E.g., w = 1,2 or 3.
print("sksks", type(X))
# print(y)
# print(X.dtypes) 

# X = [[0.4,0.3],[0.6,0.25],[0.7,0.6], [0.9, 0.65], [.5,.29], [.65,.5]]
# # y = [[1],[1],[0],[0],[0], [0]]
# y = {1, 1, 0, 0, 0, 0}
# print(y.shape)

print(X.min)
print(X.max)
print(y)

sksks <class 'pandas.core.frame.DataFrame'>
<bound method NDFrame._add_numeric_operations.<locals>.min of        Displacement  Force    Work
0                 4   0.00    0.00
1                 3   0.00    0.00
2                 0   0.00    0.00
3                 3   0.00    0.00
4                 2   0.00    0.00
...             ...    ...     ...
10795            10  21.40  213.95
10796             9  21.44  192.93
10797             8  21.44  171.50
10798            10  21.44  214.37
10799             9  21.40  192.56

[10800 rows x 3 columns]>
<bound method NDFrame._add_numeric_operations.<locals>.max of        Displacement  Force    Work
0                 4   0.00    0.00
1                 3   0.00    0.00
2                 0   0.00    0.00
3                 3   0.00    0.00
4                 2   0.00    0.00
...             ...    ...     ...
10795            10  21.40  213.95
10796             9  21.44  192.93
10797             8  21.44  171.50
10798            10  21.44  214.37


In [109]:
scaler_min_max = MinMaxScaler(feature_range=(0.001, .99))
X_norm = scaler_min_max.fit_transform(X)

# print(X_norm.shape)
# print(X_norm)


print(X.min)
# My created norm
# X_norm = (X-X.min())/(X.max()-X.min())
# X_norm = X_norm.values
# print(X_norm.shape)
# print(X_norm)



<bound method NDFrame._add_numeric_operations.<locals>.min of        Displacement  Force    Work
0                 4   0.00    0.00
1                 3   0.00    0.00
2                 0   0.00    0.00
3                 3   0.00    0.00
4                 2   0.00    0.00
...             ...    ...     ...
10795            10  21.40  213.95
10796             9  21.44  192.93
10797             8  21.44  171.50
10798            10  21.44  214.37
10799             9  21.40  192.56

[10800 rows x 3 columns]>


In [110]:
# Split the data between train and test. 
X_train, X_test, y_train, y_test = train_test_split( X_norm, y, test_size=0.33, random_state=42) # Split the data to 33% to test, and 66% to training
                                            #These value come in four 66X1 matrices for X_train and X_test
                                            # and one 66X1 matrix for y_train and y_test. 
                                            # random state = 42
print(" This is X_train \n", X_train, "\n" )
print(" This is X_test \n", X_test, "\n" )
print(" This is y_train \n", y_train, "\n" )
print(" This is y_test \n", y_test, "\n" )


# print("X train \n", X_train)
# # print("Y train \n", y_train)
# # print("X train len \n", len(X_train))
# # print("Y train len \n", len(y_train))
# print("X train shape \n", X_train.shape)
# print("Y train shape\n", y_train.shape)


# print("X test 1 \n", X_test)
# # print("Y test 1 \n", y_test)
# # print("X test len \n", len(X_test))
# # print("Y test len \n", len(y_test))
# print("X test shape \n", X_test.shape)
# print("Y test shape\n", y_test.shape)

print("X train shape \n", X_train.shape)
print("Y train shape\n", y_train.shape)

print("X test shape \n", X_test.shape)
print("Y test shape\n", y_test.shape)

 This is X_train 
 [[0.116      0.6838749  0.08049236]
 [0.06105556 0.001      0.001     ]
 [0.08661111 0.4526933  0.04014698]
 ...
 [0.162      0.67447521 0.11074153]
 [0.03933333 0.001      0.001     ]
 [0.53255556 0.49816748 0.26848151]] 

 This is X_test 
 [[0.11216667 0.52966915 0.0605027 ]
 [0.36005556 0.63535217 0.23154732]
 [0.37538889 0.96027665 0.36458914]
 ...
 [0.49422222 0.96357924 0.48157562]
 [0.53383333 0.51391831 0.27766355]
 [0.36644444 0.66075674 0.2450202 ]] 

 This is y_train 
 5792    5
678     1
2577    3
6839    6
3098    3
       ..
5734    5
5191    5
5390    5
860     1
7270    7
Name: Label, Length: 7236, dtype: int64 

 This is y_test 
 1254     2
9033     8
2523     3
10670    9
8637     8
        ..
10522    9
9260     8
3945     4
7333     7
9277     8
Name: Label, Length: 3564, dtype: int64 

X train shape 
 (7236, 3)
Y train shape
 (7236,)
X test shape 
 (3564, 3)
Y test shape
 (3564,)


In [111]:
y_train, y_test = y_train.values, y_test.values # Transpose the y_train and y_test data. 
                                # Essentailly we go from a 66X1 matrices to a 1x66 matrices. 
X_train, X_test = X_train.T, X_test.T # Transpose the X_train and X_test data. 
                                # Essentailly we go from four 66X1 matrices to four 1x66 matrices. 
# print(" This is X_train.T \n", X_train, "\n" )
# print(" This is X_test.T \n", X_test, "\n" )
# print(" This is y_train.values \n", y_train, "\n" )
# print(" This is y_test.values \n", y_test, "\n" )



print("X train \n", X_train)
print("Y train \n", y_train)

print("X test 1 \n", X_test)
print("Y test 1 \n", y_test)


# print("X train len \n", len(X_train))
# print("Y train len \n", len(y_train))
print("X train shape \n", X_train.shape)
print("Y train shape\n", y_train.shape)



# # # print("X test len \n", len(X_test))
# print("Y test len \n", len(y_test))
print("X test shape \n", X_test.shape)
print("Y test shape\n", y_test.shape)

X train 
 [[0.116      0.06105556 0.08661111 ... 0.162      0.03933333 0.53255556]
 [0.6838749  0.001      0.4526933  ... 0.67447521 0.001      0.49816748]
 [0.08049236 0.001      0.04014698 ... 0.11074153 0.001      0.26848151]]
Y train 
 [5 1 3 ... 5 1 7]
X test 1 
 [[0.11216667 0.36005556 0.37538889 ... 0.49422222 0.53383333 0.36644444]
 [0.52966915 0.63535217 0.96027665 ... 0.96357924 0.51391831 0.66075674]
 [0.0605027  0.23154732 0.36458914 ... 0.48157562 0.27766355 0.2450202 ]]
Y test 1 
 [2 8 3 ... 4 7 8]
X train shape 
 (3, 7236)
Y train shape
 (7236,)
X test shape 
 (3, 3564)
Y test shape
 (3564,)


In [112]:

# # # --- Declare network --- "
nn = ReflexFuzzyNeuroNetwork(gamma=1, theta=.1)
# '''
# X_trian after the X_train.T (transponse) is an "array [[column 1,column 2, column 3, column 4"]]
# y_train after the y_train.values (transpose) is an array[column 5]
# '''
# --- Train network --- #
nn.train(X_train, y_train)

In [113]:
# import sys
# import numpy
# numpy.set_printoptions(threshold=sys.maxsize)

# --- Test Network --- #
y_predlr = nn.test(X_test,y_test)
# print(nn.query([0.22,0.62,.067,0.04]))

print(y_predlr)
print(type(y_predlr))


print(y_test)
print(type(y_test))



KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import confusion_matrix

import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

print(y_predlr)
print(type(y_predlr))
print(len(y_predlr))

print(y_test)
print(type(y_test))
print(len(y_test))





In [ ]:

# y_test2 = np.array_str(y_test)

# # print(np.fromstring(y_test2, dtype=str))
# # print(y_test)
# # print(type(y_test2))

# print(len(y_predlr))


# print(len(y_test))

confusion_matrix(y_test, y_predlr)



In [ ]:
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score, matthews_corrcoef

# unique_labels(y_train)
unique_labels(y_test)

In [ ]:
def plot(y_true, y_pred):
    labels = unique_labels(y_test)
    column = [f'Predicted {label}' for label in labels]
    indices = [f'Actual {label}' for label in labels]
    table = pd.DataFrame(confusion_matrix(y_true, y_pred), columns = column, index=indices)

    return table


plot(y_test, y_predlr)

In [ ]:
import seaborn as sns

def plot2(y_true, y_pred):
    labels = unique_labels(y_test)
    column = [f'Predicted {label}' for label in labels]
    indices = [f'Actual {label}' for label in labels]
    table = pd.DataFrame(confusion_matrix(y_true, y_pred), columns = column, index=indices)

    return sns.heatmap(table, annot = True, fmt = 'd', cmap= 'viridis')

plot2(y_test, y_predlr)

accuracy_score1 = accuracy_score(y_test, y_predlr)
print(accuracy_score1)


In [ ]:

# accuracy_score = accuracy_score(y_test, y_predlr)
# print(accuracy_score)

# precision_score = precision_score(y_test, y_predlr)

# f1_score = f1_score(y_test, y_predlr)
# print(f1_score)

# fbeta_score = fbeta_score(y_test, y_predlr, beta=0.5)
# print("beta = 0.5", fbeta_score)

# fbeta_score(y_test, y_predlr, beta=2)
# print("beta = 2", fbeta_score)

# matthews_corrcoef = matthews_corrcoef(y_test, y_predlr)
# print(matthews_corrcoef)

In [ ]:
# %matplotlib ipympl


# import time
# import serial
# import matplotlib.pyplot as plt
# import matplotlib.animation as animation
# import numpy as np

# def animate(i, dataList, ser):
      

#         ser.write(b'g')                                     # Transmit the char 'g' to receive the Arduino data point
#         arduinoData_string = ser.readline().decode('ascii') # Decode receive Arduino data as a formatted string
#         a = list(map(str.strip, arduinoData_string.split(',')))
       
#         #print(i)                                           # 'i' is a incrementing variable based upon frames = x argument

#         # print(type(arduinoData_string))

#         try:
#                 # arduinoData_float = float(arduinoData_string)   # Convert to float
#                 # print("This is Arduino Data ", arduinoData_float)
#                 # print("This is Arduino Data type ", type(arduinoData_float), "\n")

#                 # dataList.append(arduinoData_float)
#                 # print("This is dataList", dataList)
#                 # print("This is dataList type ", type(dataList), "\n")

#                 b = [float(i) for i in a]
#                 print(b)
#                 print(type(b))  
#                 c = b[0]+ b[1]+ b[2]
#                 print(c)
#                 print(type(c))
#                 dataList.append(c)
                
#                 # b = [float(i) for i in a]
#                 # norm_ful = (b-X.min())/(X.max()-X.min())
#                 # norm_ful = norm_ful.values
#                 # print(norm_ful)
#                 # prediction = nn.predict(norm_ful)
#                 # print(prediction)
#                 # dataList.append(prediction)              # Add to the list holding the fixed number of points to animate
              
#         except:                                             # Pass if data point is bad                               
#                 pass    

#         dataList = dataList[-50:]                           # Fix the list size so that the animation plot 'window' is x number of points

#         ax.clear()                                          # Clear last data frame
#         ax.plot(dataList)                                   # Plot new data frame

#         ax.set_ylim([0, 1200])                              # Set Y axis limit of plot
#         ax.set_title("Arduino Data")                        # Set title of figure
#         ax.set_ylabel("Value")                              # Set title of y axis 

# dataList = []                                           # Create empty list variable for later use
                                                        
# fig = plt.figure()                                      # Create Matplotlib plots fig is the 'higher level' plot window
# ax = fig.add_subplot(111)                               # Add subplot to main fig window

# ser = serial.Serial("COM10", 9600)                       # Establish Serial object with COM port and BAUD rate to match Arduino Port/rate
# print(ser)

# time.sleep(2)                                           # Time delay for Arduino Serial initialization 

#                                                         # Matplotlib Animation Fuction that takes takes care of real time plot.
#                                                         # Note that 'fargs' parameter is where we pass in our dataList and Serial object. 
# ani = animation.FuncAnimation(fig, animate, frames=100, fargs=(dataList, ser), interval=50) 

# plt.show()                                              # Keep Matplotlib plot persistent on screen until it is closed
# ser.close()                                             # Close Serial connection when plot is closed

    

In [ ]:
# %matplotlib notebook

# import random
# import numpy as np
# import pandas as pd
# from itertools import count
# from datetime import datetime
# import time
# from matplotlib.animation import FuncAnimation
# from matplotlib.figure import Figure
# import matplotlib.pyplot as plt
# import matplotlib.patches as patches


# # cinstants and x array
# label = []
# x_label = []
# pred_x = 0

# fig = Figure(figsize = (5,5), dpi = 100)
# fig.suptitle('I-V Curve')
# ax = fig.add_subplot(111)
# ax.set_xlabel('Voltage (V)')
# ax.set_ylabel('Current (A)')
# ax.grid(color = "green", linestyle = '--', linewidth = 0.5)



# def animate(i):
#         ful = []
#         global pred_x
#         data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\Arduino_live.csv')

#         # x = data['x_value']
#         y1 = data['Displacement']
#         y2 = data['Force']
#         y3 = data['Work']


#         len1 = y1.size
#         len2 = y2.size
#         len3 = y3.size



#         ful.append(y1[len1-1])
#         ful.append(y2[len2-1])
#         ful.append(y3[len3-1])






#         norm_ful = (ful-X.min())/(X.max()-X.min())
#         norm_ful = norm_ful.values



# #         prediction = nn.predict(norm_df)

# #         # print(df)
# #         # print(X)
# #         # print(X.min())
# #         # print(X.max())
# #         print(norm_df)

# #         print(prediction)

        
#         prediction = nn.predict(norm_ful)
        

#         label.append(prediction)
#         x_label.append(pred_x)
      

#         pred_x = pred_x + 1

#         data_y = pd.Series(label)

#         data_x = pd.Series(x_label)

#         plt.cla()
#         plt.plot(data_x, data_y, label='Channel 1')
#         plt.xlim(i-30, i+10)
#         plt.ylim(y[i]-5, y[i]+5)
#         plt.legend(loc='upper left')
#         plt.tight_layout()

# ani = FuncAnimation(plt.gcf(), animate, interval = 50, blit = True)

# plt.tight_layout()
# plt.show()

In [ ]:
# df = [97, 6.48, 689.92] # this has to be the same as b
# print("This is df", df)
# print("This is type df", type(df[1]))
# norm_df = (df-X.min())/(X.max()-X.min())
# print("This is norm_df", norm_df)
# print("This is type norm_df", type(norm_df))

# norm_df = norm_df.values
# print("This is norm_df.values", norm_df)  # this has to be the same as b but with balues smaller than 1
# print("This is type norm_df.values", type(norm_df))  # this has to be the same as b but with balues smaller than 1


# prediction = nn.predict(norm_df)

# # print(df)
# # print(X)
# # print(X.min())
# # print(X.max())


# print("This is prediction", prediction) # this has to be the same as c but with balues smaller than 1
# print("This is type prediction", type(prediction)) 

# prediction1 = float(prediction.item())
# print("This is prediction", prediction1)
# print("This is type prediction", type(prediction1)) 

# print(X.min(), X.max())


# label = []
# x_label = []
# pred_x = 0

# def reflextactile(i):
#         ful = []
#         global pred_x
#         data = pd.read_csv('C:\\Users\\dema2\\OneDrive\\Desktop\\PhD\\RFMN\\Reflex-Fuzzy-Network\\Arduino_live.csv')

#         y1 = data['Range']
#         y2 = data['Force']
#         y3 = data['Work']

#         len1 = y1.size
#         len2 = y2.size
#         len3 = y3.size

#         ful.append(y1[len1-1])
#         ful.append(y2[len2-1])
#         ful.append(y3[len3-1])



#         norm_ful = (ful-X.min())/(X.max()-X.min())
#         norm_ful = norm_ful.values


#         # df = [97, 6.48, 689.92]
#         # norm_df = (df-X.min())/(X.max()-X.min())
#         # norm_df = norm_df.values


#         prediction = nn.predict(norm_ful)

#         return prediction
#         # label.append(prediction)
#         # x_label.append(pred_x)

#         # pred_x = pred_x + 1

#         # data_y = pd.Series(label)

#         # data_x = pd.Series(x_label)




In [ ]:
# import gradio as gr
# import tensorflow as tf
# import numpy as np
# import json
# from os.path import dirname, realpath, join